import "./globals.css";
import React from "react";
import { Poppins } from "next/font/google";
import dynamic from "next/dynamic";
export const metadata = {
  title: "Kassam.az",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["200", "300", "400", "500"],
  subsets: ["latin"],
});

const DynamicHeader = dynamic(() => import("../components/header/page"), {
  loading: () => <p>Loading...</p>,
});

const DynamicFooter = dynamic(() => import("../components/footer/page"), {
  loading: () => <p>Loading...</p>,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body {...poppins}>
        {/* Header */}
        <DynamicHeader />
        {/* Main */}
        {children}
        {/* Footer */}
        <DynamicFooter />
      </body>
    </html>
  );
}
