import Footer from "@/components/footer/page";
import "./globals.css";
import Header from "@/components/header/page";

export const metadata = {
  title: "Kassam.az",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Header */}
        <Header />
        {/* Main */}
        {children}
        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
